apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 5
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nginx-cfg-file
          mountPath: /etc/nginx
      volumes:
      - name: nginx-cfg-file
        configMap: 
          name: nginx-configmap 
          items:
            - key: nginx.cfg
              path: nginx.cfg
